Repository colemanw/webform_civicrm, pull requests merged in 2019-08, with the labels that each got.

#239 Use api to retrieve civi settings
  includes/utils.inc
  includes/wf_crm_admin_form.inc
  includes/wf_crm_admin_help.inc
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  src/Fields.php
Labels: 8.x

#240 Add participant to civicrm data en to webform menu
  includes/wf_crm_webform_postprocess.inc
  webform_civicrm.module
Labels: 8.x

#241 Fixed roles retrieval in webform
  src/Fields.php
Labels: 8.x

#229 Better feedback on removing CiviCRM fields
  includes/wf_crm_admin_form.inc
Labels: 8.x

#243 Remove unused function wf_crm_get_activity_types
  includes/utils.inc
Labels: 8.x, port

#230 Converted wf_crm_get_matching_rules to api only
  includes/utils.inc
Labels: 8.x

#232 Replaced wf_crm_get_events by an api only function
  includes/utils.inc
Labels: 8.x

#234 Add ability to create new case based on existing case
  includes/wf_crm_admin_form.inc
  includes/wf_crm_admin_help.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x

#225 Civicrm Contact element improvements
  includes/contact_component.inc
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_ajax.inc
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  js/webform_civicrm_forms.js
  src/Controller/AjaxController.php
  src/Element/CivicrmContact.php
  src/Fields.php
  src/Plugin/WebformElement/CivicrmContact.php
  webform_civicrm.module
Labels: 8.x

#253 Switch to api for fetching tags
  includes/contact_component.inc
  includes/utils.inc
Labels: 7.x

#248 Use attachment api instead of internal functions
  includes/wf_crm_webform_base.inc
Labels: 7.x

#257 Fix file upload jQuery selector
  js/webform_civicrm_forms.js
Labels: 8.x, port

#254 Switch to api for fetching tags
  includes/contact_component.inc
  includes/utils.inc
  src/FieldOptions.php
Labels: 8.x, port

#244 Remove legacy stuff
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  js/webform_civicrm_admin.js
  src/Fields.php
  webform_civicrm.module
Labels: 8.x, port

#96 CEW-191: Changing validateBillingFields() method to get email value as string.
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x

#236 Fix a bug when new multi-value fields are added to the webform.
  includes/wf_crm_admin_form.inc
Labels: 7.x

#260 Refactor getCustomData function to use api instead of BAO
  includes/wf_crm_webform_base.inc
Labels: 7.x, needs port

#245 Fetch fields with api instead of sql query
  includes/utils.inc
  includes/wf_crm_admin_component.inc
Labels: 7.x, needs port

#262 Refactor getCustomData function to use api instead of BAO
  includes/wf_crm_webform_base.inc
Labels: 8.x, port

#247 Switch to api for loading event/participant info
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
Labels: 8.x, port

#246 Switch to api for loading event/participant info
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
Labels: 7.x

#261 Begin support for autocomplete
  includes/contact_component.inc
  includes/wf_crm_webform_ajax.inc
  js/webform_civicrm_contact.js
  js/webform_civicrm_forms.js
  src/Controller/AjaxController.php
  src/Plugin/WebformElement/CivicrmContact.php
  templates/webform-civicrm-contact.html.twig
  webform_civicrm.libraries.yml
  webform_civicrm.module
Labels: 8.x
