Repository colemanw/webform_civicrm, pull requests merged in 2020-10, with the labels that each got.

#365 Revert "Use entity functions to save custom data"
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x, port

#367 Migrate contact_component.inc to services
  includes/contact_component.inc
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_ajax.inc
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  src/ContactComponent.php
  src/ContactComponentInterface.php
  src/Plugin/WebformElement/CivicrmContact.php
  webform_civicrm.services.yml
Labels: 8.x

#366 Use entity functions to save custom data
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#371 D8 - Use entity functions to save custom data
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x

#370 Issue#3174133: Allow static widget to use values other than default value
  includes/contact_component.inc
Labels: 7.x
