Repository colemanw/webform_civicrm, pull requests merged in 2020-08, with the labels that each got.

#331 Add CRM.payment.getTotalAmount() function (fix for PayPal / Stripe)
  js/webform_civicrm_payment.js
Labels: 7.x, needs port

#333 Fix Custom Groups Missing for Contact Subtypes.
  includes/wf_crm_admin_form.inc
Labels: 8.x, bug

#328 Support computed elements across multiple pages
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x

#334 Add CRM.payment.getTotalAmount() function (port of #331)
  js/webform_civicrm_payment.js
Labels: 8.x, port

#338 membership_activity_fix
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#340 D8 port of membership_activity_fix
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x

#339 group_subscriptionnotice_fix
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x

#341 Checksum port edits
  includes/contact_component.inc
  includes/wf_crm_webform_ajax.inc
Labels: 8.x

#342 Use entity functions to save custom data
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#337 CATL-1034: Allow updating case type of an existing case
  includes/wf_crm_admin_help.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#335 CATL-1564: Handle hidden (select) fields in submissions and emails
  webform_civicrm.module
Labels: 7.x, needs port
