Repository colemanw/webform_civicrm, pull requests merged in 2020-11, with the labels that each got.

#378 CATL-1711: Allow static widget to use values other than default value
  src/Plugin/WebformElement/CivicrmContact.php
Labels: 8.x, port

#377 Load cases by manager as well as client
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_preprocess.inc
Labels: 7.x, needs port

#384 Fetch domain because APIv3 does not do so reliably
  includes/wf_crm_webform_base.inc
Labels: 7.x, needs port

#386 Send state id not abbr to the dedupe function
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#372 D8 - Make email receipt independent of the contribution page
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_postprocess.inc
  webform_civicrm.install
Labels: 8.x

#369 D8 - Decouple list of payment processors from contribution page
  includes/wf_crm_admin_form.inc
  src/FieldOptions.php
  src/Fields.php
Labels: 8.x

#388 Remove contribution page dependency from the webform
  includes/wf_crm_admin_component.inc
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  js/webform_civicrm_admin.js
  src/AdminHelp.php
  src/Fields.php
  webform_civicrm.install
Labels: 8.x

#387 Update Help Text - Recurring
  src/AdminHelp.php
Labels: 8.x, needs port
