Repository colemanw/webform_civicrm, pull requests merged in 2020-12, with the labels that each got.

#397 Add missing Participant Notes field.
  src/Fields.php
Labels: 8.x, bug

#401 D8 - Add Pay Later Receipt message to receipts
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_postprocess.inc
  webform_civicrm.install
Labels: 8.x, 9.x

#406 Activities fix for default_value + activity_date_time + Add test
  includes/utils.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  src/Fields.php
  src/Plugin/WebformElement/CivicrmContact.php
  tests/src/FunctionalJavascript/ActivitySubmissionTest.php
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
Labels: 8.x, bug, has test

#413 Add source_record_id to Membership Renewal Activity
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x, needs port

#416 d7port-413
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, port

#408 Fix date time custom fields + add test for Custom Fields - type: Text and Date (w/ Time)
  includes/wf_crm_webform_preprocess.inc
  src/Fields.php
  tests/src/FunctionalJavascript/ActivitySubmissionTest.php
  tests/src/FunctionalJavascript/CiviCrmTestBase.php
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
Labels: 8.x/9.x, bug, has test

#414 Migrate wf_crm_admin_form.inc to services
  includes/wf_crm_admin_component.inc
  src/AdminForm.php
  src/AdminFormInterface.php
  src/Form/WebformCiviCRMSettingsForm.php
  webform_civicrm.module
  webform_civicrm.services.yml
Labels: 8.x/9.x

#410 Record line_item amounts without rounding.
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x/9.x, bug, needs test

#392 Set case role (relationship) start date when creating case role, update existing active case role (relationship) if it already exists
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x/9.x, bug, ported

#393 7.x Set case role (relationship) start date when creating case role, update existing active case role (relationship) if it already exists
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, port

#419 doPayment throws exceptions when payment fails. Catch and display to the user instead of an internal server error
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x/9.x, bug

#420 Remove doTransferCheckout
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x/9.x, bug

#423 7.x port of #420 (doPayment exception / doTransferCheckout)
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, bug, port

#421 Fix javascript error due to incorrect path.
  webform_civicrm.module
Labels: 8.x/9.x, bug
