Repository colemanw/webform_civicrm, pull requests merged in 2020-09, with the labels that each got.

#350 Fix autoload of event from URL
  includes/wf_crm_webform_base.inc
Labels: 8.x

#349 When updating a Case with multiple contacts, unset contact ID fields to avoid API error
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, needs port

#354 When updating a Case with multiple contacts, unset contact ID fields …
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x

#347 Fix Unsupported operand types Error
  includes/wf_crm_admin_form.inc
Labels: 8.x, bug

#352 D7 : Do not change Membership type for Inherited membership record
  includes/wf_crm_webform_base.inc
Labels: 7.x

#353 D8 : Do not change Membership type for Inherited membership record
  includes/wf_crm_webform_base.inc
Labels: 8.x

#348 Use entity functions to save custom data
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x, port

#362 Migrate help inc file to services
  includes/contact_component.inc
  includes/wf_crm_admin_form.inc
  includes/wf_crm_webform_ajax.inc
  src/AdminHelp.php
  src/AdminHelpInterface.php
  src/Form/WebformCiviCRMSettingsForm.php
  src/Plugin/WebformElement/CivicrmContact.php
  webform_civicrm.module
  webform_civicrm.services.yml
Labels: 8.x
