Repository colemanw/webform_civicrm, pull requests merged in 2021-12, with the labels that each got.

#634 D8/9 - Fix tax rate & amount display in contribution/membership receipts
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#648 Remove fixed value that makes relationship always active.
  src/Fields.php
Labels: bug, 8.x/9.x

#644 Add support for contact image.
  js/webform_civicrm_forms.js
  src/Fields.php
  src/WebformCivicrmBase.php
  src/WebformCivicrmPreProcess.php
Labels: 8.x/9.x, needs test, needs work

#639 D8/9 - Page break labels are overwritten on civicrm settings page submit
  src/AdminForm.php
Labels: bug, 8.x/9.x

#637 D8/9 render tags/symbols in status message
  src/WebformCivicrmPreProcess.php
Labels: bug, 8.x/9.x

#631 D8/9 - Allow number field to be retyped into options
  README.md
  src/Element/CivicrmNumber.php
  src/FieldOptions.php
  src/Fields.php
  src/Plugin/WebformElement/CivicrmNumber.php
  src/Plugin/WebformElement/CivicrmOptions.php
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
Labels: 8.x/9.x, has test

#649 Remove old jQuery shim leftover from Drupal7 module
  js/webform_civicrm_admin.js
  js/webform_civicrm_options.js
Labels: 8.x/9.x

#657 Switch back to webform dev.
  .github/workflows/main.yml
Labels: 8.x/9.x, test only

#651 Javascript code cleanup
  README.md
  js/webform_civicrm_admin.js
  js/webform_civicrm_payment.js
  js/webform_tab.js
Labels: 8.x/9.x

#650 Fix icons & labels in vertical tabs
  js/webform_civicrm_admin.js
Labels: 8.x/9.x

#658 Add Admin screenshot.
  tests/src/FunctionalJavascript/ContactRelationshipTest.php
Labels: 8.x/9.x, test only

#636 D8/9 - Fix the submission of a locked field when it has a default value
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: bug, 8.x/9.x, has test, mpaulso

#659 Admin Form - Fix cross-theme compatability
  js/webform_civicrm_admin.js
Labels: 8.x/9.x, user interface

#645 Duplicate email addresses created when users with an account add an email via CiviCRM webform
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x

#622 [Test only] - D8/9 - Membership pay later test
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
Labels: 8.x/9.x, test only, jitendrapurohit

#666 D8/9 - Fix ajax load of radio, checkbox and date fields
  js/webform_civicrm_forms.js
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: bug, 8.x/9.x, has test

#635 Fix inconsistencies with date fields
  js/webform_civicrm_forms.js
  src/WebformCivicrmBase.php
  src/WebformCivicrmPreProcess.php
Labels: bug, 8.x/9.x, needs test, needs work, jitendrapurohit, mpaulso

#652 D8/9 - Replace utils service with dependency injection
  src/AdminForm.php
  src/AdminHelp.php
  src/ContactComponent.php
  src/Fields.php
  src/WebformAjax.php
  src/WebformCivicrmBase.php
  src/WebformCivicrmPostProcess.php
  src/WebformCivicrmPreProcess.php
  webform_civicrm.services.yml
Labels: 8.x/9.x, improvement

#663 Cleanup old hooks
  webform_civicrm.module
Labels: 8.x/9.x

#664 Incorrect event count leads to broken line items
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#667 Add jquery.tokeninput.js to webform_civicrm
  js/jquery.tokeninput.js
  webform_civicrm.libraries.yml
Labels: bug, 8.x/9.x, improvement

#662 Fix updating records when editing a submission
  src/Plugin/WebformHandler/CivicrmWebformHandler.php
  src/WebformCivicrmBase.php
  src/WebformCivicrmPostProcess.php
  src/WebformCivicrmPostProcessInterface.php
  src/WebformCivicrmPreProcess.php
  src/WebformCivicrmPreProcessInterface.php
  tests/src/FunctionalJavascript/SubmissionEditTest.php
Labels: 8.x/9.x, has test

#655 Add AJAX contribution.
  .github/workflows/main.yml
  js/webform_civicrm_payment.js
  tests/src/FunctionalJavascript/StripeTest.php
Labels: 8.x/9.x, needs test, needs work

#669 don't disable state/province fields when existing contact exists
  js/webform_civicrm_forms.js
Labels: bug, 8.x/9.x

#632 Evaluate checksum on webform submit
  src/AdminForm.php
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x, needs test

#633 Multiple Case role selection on case configuration
  src/Fields.php
Labels: bug, 8.x/9.x, needs test

#668 D8/9 - Include webform receipt values in contribution emails
  .github/workflows/main.yml
  src/Utils.php
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/MultiCustomFieldsSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
  webform_civicrm.module
Labels: bug, 8.x/9.x, has test

#672 Moving back to testing against CiviCRM dev-master.
  .github/workflows/main.yml
Labels: 8.x/9.x, test only
