Repository colemanw/webform_civicrm, pull requests merged in 2021-05, with the labels that each got.

#534 D8/9 Replace CiviCRM billing fields with Webform fields.
  js/webform_civicrm_forms.js
  js/webform_civicrm_payment.js
  src/AdminForm.php
  src/Controller/AjaxController.php
  src/FieldOptions.php
  src/Fields.php
  src/Utils.php
  src/WebformAjax.php
  src/WebformCivicrmBase.php
  src/WebformCivicrmPostProcess.php
  src/WebformCivicrmPreProcess.php
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/EventTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
  webform_civicrm.install
  webform_civicrm.routing.yml
Labels: 8.x/9.x, has test

#539 D8/9 - Fix pagebreaks on webforms
  src/AdminForm.php
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/EventTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/StripeTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, has test

#547 [Testing only] - Remove need to specify scssphp version now that compatiable civicrm c…
  .github/workflows/main.yml
Labels: 8.x/9.x

#548 require any email for contact 1 for billing, not just email 1
  js/webform_civicrm_admin.js
Labels: 8.x/9.x

#545 D8/9 Fix save on setting page if an element is deleted
  src/AdminForm.php
  tests/src/FunctionalJavascript/SaveSettingsTest.php
Labels: 8.x/9.x, bug, has test

#540 D8/9 - [Test Only] - Add test for participant contact reference field
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
  tests/src/FunctionalJavascript/EventTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, has test

#543 D8/9 Fix relationship type load on settings page
  js/webform_civicrm_admin.js
Labels: 8.x/9.x, bug

#552 D8/9 - Enable billing address by default when contribution is enabled
  src/AdminForm.php
Labels: 8.x/9.x

#556 D8/9 - Fix duplicates in multi-contact ref records
  src/WebformCivicrmPostProcess.php
Labels: 8.x/9.x, bug, needs test

#551 Revert "require any email for contact 1 for billing, not just email 1"
  js/webform_civicrm_admin.js
Labels: 8.x/9.x

#554 Use text_format type.
  src/Utils.php
Labels: 8.x/9.x, bug

#558 D8/9 - Fix duplicates in multi-contact ref records
  src/WebformCivicrmPostProcess.php
Labels: 8.x/9.x, bug, has test, needs port
