Repository colemanw/webform_civicrm, pull requests merged in 2021-09, with the labels that each got.

#604 Don't create a blank billing address or email
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#606 D8/9 - Fix fatal error on gender field
  src/Element/CivicrmSelectOptions.php
Labels: bug, 8.x/9.x

#596 Update Github Testing Matrix
  .github/workflows/main.yml
Labels: 8.x/9.x

#607 D8/9 - Fix submission on disabled/locked fields on the webform
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#608 D8/9 - Add test for membership + contribution + line item with taxes
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, test only, KarinG

#610 Port #420 - Remove doTransferCheckout
  includes/wf_crm_webform_postprocess.inc
Labels: ported

#609 Annotate Contribution + Line Item + Memberships Test.
  .github/workflows/main.yml
  tests/src/FunctionalJavascript/ContactRelationshipTest.php
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, test only, jitendrapurohit

#612 D8/9 - Fix error on selecting country with numeric state abbreviation
  src/Utils.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
Labels: bug, 8.x/9.x, has test

#614 [Test only] - Add sales tax by province test
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: has test

#615 D8/9 - Fix icons display on webform admin screen
  js/webform_civicrm_admin.js
  src/AdminForm.php
Labels: bug, 8.x/9.x

#611 Need to map is_recur for payment processors not using propertyBag.
  src/Utils.php
Labels: bug, 8.x/9.x, needs test

#617 Adding recurring test -> check for Payment Token.
  tests/src/FunctionalJavascript/ContributionIatsTest.php
Labels: 8.x/9.x, has test
