Repository colemanw/webform_civicrm, pull requests merged in 2021-10, with the labels that each got.

#619 D8/9 - Group filter on autocomplete widget produces error on the webform.
  src/Plugin/WebformElement/CivicrmContact.php
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
Labels: bug, 8.x/9.x, has test

#605 D8/9 - Remove contact paging if it is disabled from additional options
  src/AdminForm.php
  src/Utils.php
  tests/src/FunctionalJavascript/SaveSettingsTest.php
Labels: bug, 8.x/9.x, MegaphoneJon

#623 specify drupal-8 version
  .github/workflows/main.yml
  composer.json
Labels: 8.x/9.x, test only

#624 [Ad-hoc PR] - Temporary workaround for restriction in composer.json
  .github/workflows/main.yml
Labels: 8.x/9.x, test only

#627 Fix test failures after #626
  .github/workflows/main.yml
  README.md
  src/Plugin/WebformElement/CivicrmContact.php
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, test only

#629 Update main.yml -> new D9 branch + update RC version.
  .github/workflows/main.yml
Labels: 8.x/9.x, test only

#630 Specify @dev version
  .github/workflows/main.yml
Labels: 8.x/9.x, test only
