Repository colemanw/webform_civicrm, pull requests merged in 2021-01, with the labels that each got.

#425 8x port - Fetch domain because APIv3 does not do so reliably
  includes/wf_crm_webform_base.inc
Labels: 8.x/9.x

#426 Typo fix in warning message.
  src/ContactComponent.php
Labels: 8.x/9.x, bug, needs test

#427 Expanding Activity Test
  src/Fields.php
  tests/src/FunctionalJavascript/ActivitySubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, bug, has test

#428 Add Dedupe + Contact (Sub) Type Test
  includes/wf_crm_webform_postprocess.inc
  tests/src/FunctionalJavascript/ContactDedupeTest.php
Labels: 8.x/9.x, bug, has test

#432 Allow to translate `Payment Information` string
  includes/wf_crm_webform_preprocess.inc
Labels: 8.x/9.x, bug

#430 Add ActivityDetails check.
  tests/src/FunctionalJavascript/ActivitySubmissionTest.php
Labels: 8.x/9.x, has test

#435 Fix Claro theme fieldset conflict.
  src/Plugin/WebformElement/CivicrmContact.php
Labels: 8.x/9.x, bug

#429 Add Relationship Test.
  src/Utils.php
  tests/src/FunctionalJavascript/ContactDedupeTest.php
  tests/src/FunctionalJavascript/ContactRelationshipTest.php
Labels: 8.x/9.x, bug, has test

#434 Update civicrm versions and copy over Transaction API into webform civicrm code base
  .github/workflows/main.yml
  src/Utils.php
  tests/src/FunctionalJavascript/CiviCrmTestBase.php
  tests/src/FunctionalJavascript/ContributionPageTest.php
Labels: 8.x/9.x, bug, has test

#441 Separate Tests for Individual Payment Processors.
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
Labels: 8.x/9.x, has test

#438 Update includes/wf_crm_webform_ajax.inc to use services
  includes/wf_crm_webform_base.inc
  includes/wf_crm_webform_postprocess.inc
  includes/wf_crm_webform_preprocess.inc
  src/Controller/AjaxController.php
  src/Plugin/WebformHandler/CivicrmWebformHandler.php
  src/WebformAjax.php
  src/WebformAjaxInterface.php
  webform_civicrm.module
  webform_civicrm.services.yml
Labels: 8.x/9.x

#442 Port of PR440.
  includes/wf_crm_webform_postprocess.inc
Labels: 8.x/9.x, bug, ported

#440 Fix saving of activity tag when a tag is selected in activity settings but it is not 'user select'
  includes/wf_crm_webform_postprocess.inc
Labels: 7.x, bug, ported

#437 Update contribution transact code to use version from contributiontransactlegacy extension
  src/Utils.php
Labels: 8.x/9.x, needs test

#436 Adding test for Custom Fields of type: Checkboxes.
  src/Plugin/WebformElement/CivicrmOptions.php
  src/Plugin/WebformElement/CivicrmSelect.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
Labels: 8.x/9.x, has test

#446 D8 - Link recurring contribution to membership record if we have one
  src/WebformCivicrmPostProcess.php
Labels: 8.x/9.x, port

#447 [Test only] - Very first test for ExistingContactElement.
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
Labels: 8.x/9.x, has test

#445 Fix notice error when total amount is enabled on the webform
  src/WebformCivicrmPreProcess.php
Labels: 8.x/9.x, bug

#450 Replace all leftover Decoded with DecodedAndFlattened.
  src/AdminForm.php
  src/Plugin/WebformHandler/CivicrmWebformHandler.php
  src/WebformCivicrmPostProcess.php
  webform_civicrm.module
Labels: 8.x/9.x

#451 Test to assert membership autorenew
  tests/src/FunctionalJavascript/ContributionDummyTest.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, has test

#449 Disable clone references for now.
  src/AdminForm.php
Labels: 8.x/9.x

#452 Fix static widget for existing contact element
  js/webform_civicrm_forms.js
  src/ContactComponent.php
  src/Plugin/WebformElement/CivicrmContact.php
  src/WebformCivicrmPreProcess.php
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
  webform_civicrm.module
Labels: 8.x/9.x, has test
