Repository colemanw/webform_civicrm, pull requests merged in 2022-04, with the labels that each got.

#729 fix formatting on 'no results' result for existing contact widget
  README.md
  js/webform_civicrm_contact.js
  src/ContactComponent.php
  src/WebformAjax.php
  webform_civicrm.module
Labels: bug, 8.x/9.x, needs port

#730 D7 - Fix no result formatting on existing contact widget
  includes/contact_component.inc
  includes/wf_crm_webform_ajax.inc
  js/webform_civicrm_forms.js
Labels: 7.x, ported

#714 Update for use of FormState.
  src/AdminForm.php
  tests/src/FunctionalJavascript/ContactDedupeTest.php
Labels: 8.x/9.x

#731 add civicarrot.json
  tests/civicarrot.json
  tests/src/FunctionalJavascript/CaseSubmissionTest.php
Labels: 8.x/9.x, cool stuff, test only

#688 D8/9 - Fatal error on webform submission if it has a radio button element wi…
  src/Plugin/WebformElement/CivicrmOptions.php
  src/Utils.php
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
Labels: bug, 8.x/9.x, has test, stesi561
