Repository colemanw/webform_civicrm, pull requests merged in 2022-06, with the labels that each got.

#751 Allow discounts i.e. negative lineitems
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#754 Don't hide details of the deprecations
  .github/workflows/main.yml
Labels: test only

#756 D8/9 - Add test to capture case update error
  tests/src/FunctionalJavascript/CaseSubmissionTest.php
Labels: 8.x/9.x, test only
