Repository colemanw/webform_civicrm, pull requests merged in 2022-01, with the labels that each got.

#673 D8/9 - Incorrect labels on line item table when displayed on single page
  js/webform_civicrm_payment.js
  tests/src/FunctionalJavascript/ContributionDummyTest.php
Labels: bug, 8.x/9.x, has test

#674 Highlight token input field in case of an error
  css/token-input.css
  js/webform_civicrm_contact.js
Labels: bug, 8.x/9.x

#692 D7 - Fix PHP notices when there are no billing address fields
  includes/wf_crm_webform_postprocess.inc
Labels: bug, 7.x

#681 Test fix with drupal 9.3
  .github/workflows/main.yml
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: 8.x/9.x, test only

#689 Refs #3260975 replaces Deprecated call to drupal_set_message
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x
