Repository colemanw/webform_civicrm, pull requests merged in 2022-08, with the labels that each got.

#767 D8/9 - Fix locked field submission of state_province
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/LocationTypeTest.php
Labels: bug, 8.x/9.x, has test

#770 WIP - D10 - rector changes for drupal 10 compatibility
  src/ContactComponent.php
  src/WebformAjax.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
  tests/src/FunctionalJavascript/GrantTest.php
  tests/src/FunctionalJavascript/SaveSettingsTest.php
  tests/src/Kernel/FieldOptionsTest.php
  webform_civicrm.module
Labels: 10.x

#742 D8/9 - Fix source field to display on the contact widget using v4 api
  src/ContactComponent.php
  src/Utils.php
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: bug, 8.x/9.x, has test

#771 Small ad-hoc commit needed to allow negative amounts on the same page.
  js/webform_civicrm_payment.js
Labels: 8.x/9.x

#777 Reset test-matrix.
  .github/workflows/main.yml
Labels: 8.x/9.x, has test

#785 D8/9 - Fix source field to display on the contact widget using v4 api
  src/ContactComponent.php
  src/Utils.php
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: bug, 8.x/9.x, has test

#773 D10 - Replace jquery.once with new once API
  README.md
  js/contact_component.js
  js/webform_civicrm_admin.js
  js/webform_civicrm_contact.js
  js/webform_civicrm_forms.js
  js/webform_civicrm_options.js
  js/webform_civicrm_payment.js
Labels: needs work, 10.x

#775 translate "Existing Contact" element's properties
  src/Plugin/WebformElement/CivicrmContact.php
Labels: 8.x/9.x

#789 Suppress htmloutput links in actions run output
  .github/workflows/main.yml
Labels: test only
