Repository colemanw/webform_civicrm, pull requests merged in 2022-03, with the labels that each got.

#718 D8/9 - Make Amount Requested default + required on Grant section
  src/AdminForm.php
  src/Fields.php
Labels: bug, 8.x/9.x

#721 D7 - port #719 - check for grant in the ext
  includes/utils.inc
Labels: 7.x, ported

#724 D8/9 - Add test for grant submission.
  tests/src/FunctionalJavascript/GrantTest.php
Labels: 8.x/9.x, test only

#725 Update matrix
  .github/workflows/main.yml
  src/AdminForm.php
  tests/src/FunctionalJavascript/ContactDedupeTest.php
Labels: 8.x/9.x, has test

#723 Add maximum field length where applicable
  src/Fields.php
Labels: 8.x/9.x, cool stuff, improvement

#711 Allow sorting events by title
  src/AdminForm.php
  src/Utils.php
Labels: 8.x/9.x, improvement

#683 allow correct loading of 'Show Public Events'
  src/AdminForm.php
Labels: bug, 8.x/9.x

#727 constrain to 2.2 for now
  .github/workflows/main.yml
Labels: 8.x/9.x, test only
