Repository colemanw/webform_civicrm, pull requests merged in 2022-05, with the labels that each got.

#736 D8/9 - Allow -User Select- on Contribution Financial type field
  src/AdminForm.php
  src/Fields.php
  src/Utils.php
  tests/src/FunctionalJavascript/ContributionPayLaterTest.php
  webform_civicrm.module
Labels: 8.x/9.x, has test, improvement

#741 Fix Exception when Donation financial type isn't available in civicrm
  src/AdminForm.php
  src/Fields.php
Labels: bug, 8.x/9.x

#743 D8/9 - Fix checkbox display when rendering using Gin
  js/webform_civicrm_contact.js
Labels: bug, 8.x/9.x

#738 D8/9 - billing state is not saved on webform submission
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
Labels: bug, 8.x/9.x, has test

#745 D8/9 - Fix contact subtype for dedupe check
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/ContactDedupeTest.php
Labels: bug, 8.x/9.x

#746 D8/9 - Fix required error on static widget
  src/ContactComponent.php
  src/Plugin/WebformElement/CivicrmContact.php
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: bug, 8.x/9.x, has test

#748 Updating test-matrix to include the latest.
  .github/workflows/main.yml
Labels: 8.x/9.x, has test, test only
