Repository colemanw/webform_civicrm, pull requests merged in 2023-08, with the labels that each got.

#899 see if this fixes chromedriver download problem
  .github/workflows/main.yml
Labels: test only

#897 Multi-page webform invalid data with image
  src/WebformCivicrmPreProcess.php
Labels: bug, 8.x/9.x

#896 D9 - Set default currency on the contribution tab
  src/AdminForm.php
Labels: bug, 8.x/9.x

#686 D8/9 - Fix default load of custom value when it is set to null in civicrm
  src/WebformCivicrmPreProcess.php
  tests/src/FunctionalJavascript/CustomFieldSubmissionTest.php
Labels: bug, 8.x/9.x, has test
