Repository colemanw/webform_civicrm, pull requests merged in 2023-03, with the labels that each got.

#854 update test matrix - Feb 2023
  .github/workflows/main.yml
  tests/src/FunctionalJavascript/MembershipSubmissionTest.php
Labels: test only

#855 [test only] Switch to downloading extensions in the yml
  .github/workflows/main.yml
  tests/src/FunctionalJavascript/ContactSubmissionTest.php
  tests/src/FunctionalJavascript/ContributionIatsTest.php
  tests/src/FunctionalJavascript/StripeTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: test only

#849 [test only] Make expandy section work in drupal 10 for edit contact tests
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
  tests/src/FunctionalJavascript/WebformCivicrmTestBase.php
Labels: test only, 10.x

#850 [test only] Fix token test in drupal 10
  .github/workflows/d10.yml
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
Labels: test only, 10.x

#851 [test only] Need dev version of parent webform and other updates to github d10 action yml
  .github/workflows/d10.yml
Labels: test only, 10.x

#852 Update info.yml to support drupal 10
  tests/modules/webform_civicrm_test/webform_civicrm_test.info.yml
  webform_civicrm.info.yml
Labels: 10.x

#856 [test only] Bring drupal 10 testing into main
  .github/workflows/d10.yml
  .github/workflows/main.yml
Labels: test only

#857 [test only] drupal 10 patch no longer needed
  .github/workflows/main.yml
Labels: test only

#837 Empty array set in default values causes issue with API4 when rendering the form
  src/ContactComponent.php
Labels: bug, 8.x/9.x, needs test

#860 needs -s
  src/WebformCivicrmPostProcess.php
Labels: bug, 8.x/9.x

#859 D9 - Add Test for PR#837
  tests/src/FunctionalJavascript/LocationTypeTest.php
Labels: 8.x/9.x, test only

#858 D9 - Add upgrade code to fix lowercase contact subtype stored in settings
  webform_civicrm.install
Labels: bug, 8.x/9.x
