Repository colemanw/webform_civicrm, pull requests merged in 2023-09, with the labels that each got.

#906 [NFC] hack for chromedriver no longer needed
  .github/workflows/main.yml
Labels: test only

#905 [NFC] update testing versions
  .github/workflows/main.yml
Labels: test only

#908 Add reset for birth_date.
  js/webform_civicrm_forms.js
Labels: 8.x/9.x

#911 D9/10 - Add setting to disable primary participant for Contact 1
  src/AdminForm.php
  src/AdminHelp.php
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/EventTest.php
Labels: 8.x/9.x, has test, improvement

#909 D8/9 - Enable HTML on autocomplete field
  js/webform_civicrm_contact.js
Labels: bug, 8.x/9.x

#895 Add option to enable public groups on the webform
  src/AdminForm.php
  src/FieldOptions.php
  src/WebformCivicrmPostProcess.php
  tests/src/FunctionalJavascript/GroupsTagsSubmissionTest.php
Labels: 8.x/9.x, has test, improvement

#880 D9 - WSOD when editing results and pseudoconstant labels don't match Civi
  src/WebformCivicrmPostProcess.php
  webform_civicrm.module
Labels: bug, 8.x/9.x

#873 Add option for tokenised view link in activity details
  src/AdminForm.php
  src/WebformCivicrmPostProcess.php
Labels: 8.x/9.x, improvement
