Repository colemanw/webform_civicrm, pull requests merged in 2024-05, with the labels that each got.

#941 Fix state display on preview
  src/Plugin/WebformElement/CivicrmOptions.php
  tests/src/FunctionalJavascript/ExistingContactElementTest.php
Labels: MegaphoneJon, 10.x

#961 D9/10 - Add test for ajax payment using iats
  tests/src/FunctionalJavascript/ContributionIatsTest.php
Labels: test only

#953 wc-3423739/3423740 - fix re-ordering options in CiviCRM Options control
  src/Element/CivicrmSelectOptions.php
Labels: bug, 8.x/9.x

#965 smarty4
  .github/workflows/main.yml
Labels: test only

#969 drupal 11 readiness
  .github/workflows/main.yml
Labels: test only
